version: '3.8'
services:
  core:
    container_name: connect-authx-core
    image: ghcr.io/mrexmelle/connect-authx:0.2.2
    environment:
      - APP_PROFILE=docked
    ports:
      - '8080:8080'
    networks:
      - connect_proxy_network

networks:
  connect_proxy_network:
      name: connect-network
      external: true
