version: '3.8'
services:
  db:
    container_name: connect-auth-db
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=123
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
  core:
    container_name: connect-auth-core
    image: ghcr.io/mrexmelle/connect-auth:0.1.0
    environment:
      - APP_PROFILE=docked
    ports:
      - '8080:8080'
