app:
  datasource:
    host: db
    port: 5432
    user: authx
    password: authx123
    dbname: authx
    sslmode: disable
    timezone: Asia/Jakarta
  security:
    jwt:
      secret: 1nt3rst3ll4r-*-a5tR0
      valid-minute: 90
    default-user-password: 123
  server:
    port: 8080
    