basePath: /
definitions:
  credential.PatchPasswordRequestDto:
    properties:
      current_password:
        type: string
      new_password:
        type: string
    type: object
  credential.PostRequestDto:
    properties:
      employee_id:
        type: string
      password:
        type: string
    type: object
  credential.ResponseDto:
    properties:
      status:
        type: string
    type: object
  profile.DeleteResponseDto:
    properties:
      status:
        type: string
    type: object
  profile.Entity:
    properties:
      dob:
        type: string
      ehid:
        type: string
      email_address:
        type: string
      employee_id:
        type: string
      name:
        type: string
    type: object
  profile.PatchRequestDto:
    properties:
      fields:
        additionalProperties:
          type: string
        type: object
    type: object
  profile.PatchResponseDto:
    properties:
      status:
        type: string
    type: object
  profile.ResponseDto:
    properties:
      profile:
        $ref: '#/definitions/profile.Entity'
      status:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: mrexmelle@gmail.com
  description: Authx API for Connect.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Connect Authx API
  version: "1.0"
paths:
  /credentials:
    post:
      consumes:
      - application/json
      description: Post a new credential
      parameters:
      - description: Credential Request
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/credential.PostRequestDto'
      produces:
      - application/json
      responses:
        "200":
          description: Success Response
          schema:
            $ref: '#/definitions/credential.ResponseDto'
        "500":
          description: InternalServerError
      tags:
      - Credentials
  /credentials/{employee_id}:
    delete:
      description: Delete a credential
      parameters:
      - description: Employee ID
        in: path
        name: employee_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success Response
          schema:
            $ref: '#/definitions/credential.ResponseDto'
        "500":
          description: InternalServerError
      tags:
      - Credentials
  /credentials/{employee_id}/password:
    delete:
      description: Reset a credential's password
      parameters:
      - description: Employee ID
        in: path
        name: employee_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success Response
          schema:
            $ref: '#/definitions/credential.ResponseDto'
        "500":
          description: InternalServerError
      tags:
      - Credentials
    patch:
      consumes:
      - application/json
      description: Patch a credential's password
      parameters:
      - description: Employee ID
        in: path
        name: employee_id
        required: true
        type: string
      - description: Password Patch Request
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/credential.PatchPasswordRequestDto'
      produces:
      - application/json
      responses:
        "200":
          description: Success Response
          schema:
            $ref: '#/definitions/credential.ResponseDto'
        "500":
          description: InternalServerError
      tags:
      - Credentials
  /profiles/{ehid}:
    delete:
      description: Delete a profile
      parameters:
      - description: Employee Hash ID
        in: path
        name: ehid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success Response
          schema:
            $ref: '#/definitions/profile.DeleteResponseDto'
        "500":
          description: InternalServerError
      tags:
      - Profiles
    get:
      description: Get a profile
      parameters:
      - description: Employee Hash ID
        in: path
        name: ehid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success Response
          schema:
            $ref: '#/definitions/profile.ResponseDto'
        "500":
          description: InternalServerError
      tags:
      - Profiles
    patch:
      consumes:
      - application/json
      description: Patch a profile
      parameters:
      - description: Employee Hash ID
        in: path
        name: ehid
        required: true
        type: string
      - description: Profile Patch Request
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/profile.PatchRequestDto'
      produces:
      - application/json
      responses:
        "200":
          description: Success Response
          schema:
            $ref: '#/definitions/profile.PatchResponseDto'
        "500":
          description: InternalServerError
      tags:
      - Profiles
swagger: "2.0"
