basePath: /
definitions:
  credential.PatchPasswordRequestDto:
    properties:
      currentPassword:
        type: string
      newPassword:
        type: string
    type: object
  credential.PostRequestDto:
    properties:
      employeeId:
        type: string
      password:
        type: string
    type: object
  credential.ResponseDto:
    properties:
      status:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: mrexmelle@gmail.com
  description: Auth API for Connect.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Connect Auth API
  version: "1.0"
paths:
  /credentials:
    post:
      consumes:
      - application/json
      description: Post a new credential
      parameters:
      - description: Credential Request
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/credential.PostRequestDto'
      produces:
      - application/json
      responses:
        "200":
          description: Success Response
          schema:
            $ref: '#/definitions/credential.ResponseDto'
        "500":
          description: InternalServerError
      tags:
      - Credentials
  /credentials/{eid}:
    delete:
      description: Delete a credential
      parameters:
      - description: Employee ID
        in: path
        name: eid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success Response
          schema:
            $ref: '#/definitions/credential.ResponseDto'
        "500":
          description: InternalServerError
      tags:
      - Credentials
  /credentials/{eid}/password:
    delete:
      description: Reset a credential's password
      parameters:
      - description: Employee ID
        in: path
        name: eid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success Response
          schema:
            $ref: '#/definitions/credential.ResponseDto'
        "500":
          description: InternalServerError
      tags:
      - Credentials
    patch:
      description: Patch a credential's password
      parameters:
      - description: Employee ID
        in: path
        name: eid
        required: true
        type: string
      - description: Patch Password Request
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/credential.PatchPasswordRequestDto'
      produces:
      - application/json
      responses:
        "200":
          description: Success Response
          schema:
            $ref: '#/definitions/credential.ResponseDto'
        "500":
          description: InternalServerError
      tags:
      - Credentials
swagger: "2.0"
