basePath: /
definitions:
  github_com_mrexmelle_connect-authx_internal_dto.ServiceError:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  internal_credential.DeleteResponseDto:
    properties:
      error:
        $ref: '#/definitions/github_com_mrexmelle_connect-authx_internal_dto.ServiceError'
    type: object
  internal_credential.PatchPasswordRequestDto:
    properties:
      current_password:
        type: string
      new_password:
        type: string
    type: object
  internal_credential.PatchPasswordResponseDto:
    properties:
      error:
        $ref: '#/definitions/github_com_mrexmelle_connect-authx_internal_dto.ServiceError'
    type: object
  internal_credential.PostRequestDto:
    properties:
      employee_id:
        type: string
      password:
        type: string
    type: object
  internal_credential.PostResponseDto:
    properties:
      error:
        $ref: '#/definitions/github_com_mrexmelle_connect-authx_internal_dto.ServiceError'
    type: object
  internal_profile.DeleteResponseDto:
    properties:
      error:
        $ref: '#/definitions/github_com_mrexmelle_connect-authx_internal_dto.ServiceError'
    type: object
  internal_profile.Entity:
    properties:
      dob:
        type: string
      ehid:
        type: string
      email_address:
        type: string
      employee_id:
        type: string
      name:
        type: string
    type: object
  internal_profile.GetEhidResponseDto:
    properties:
      data:
        type: string
      error:
        $ref: '#/definitions/github_com_mrexmelle_connect-authx_internal_dto.ServiceError'
    type: object
  internal_profile.GetResponseDto:
    properties:
      data:
        $ref: '#/definitions/internal_profile.Entity'
      error:
        $ref: '#/definitions/github_com_mrexmelle_connect-authx_internal_dto.ServiceError'
    type: object
  internal_profile.PatchRequestDto:
    properties:
      fields:
        additionalProperties:
          type: string
        type: object
    type: object
  internal_profile.PatchResponseDto:
    properties:
      error:
        $ref: '#/definitions/github_com_mrexmelle_connect-authx_internal_dto.ServiceError'
    type: object
  internal_session.PostRequestDto:
    properties:
      employee_id:
        type: string
      password:
        type: string
    type: object
  internal_session.PostResponseDto:
    properties:
      data:
        $ref: '#/definitions/internal_session.SigningResult'
      error:
        $ref: '#/definitions/github_com_mrexmelle_connect-authx_internal_dto.ServiceError'
    type: object
  internal_session.SigningResult:
    properties:
      expires:
        type: string
      token:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: mrexmelle@gmail.com
  description: Authentication API for Connect.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Connect Authentication API
  version: 0.3.0
paths:
  /credentials:
    post:
      consumes:
      - application/json
      description: Post a new credential
      parameters:
      - description: Credential Request
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/internal_credential.PostRequestDto'
      produces:
      - application/json
      responses:
        "200":
          description: Success Response
          schema:
            $ref: '#/definitions/internal_credential.PostResponseDto'
        "400":
          description: BadRequest
        "500":
          description: InternalServerError
      tags:
      - Credentials
  /credentials/{employee_id}:
    delete:
      description: Delete a credential
      parameters:
      - description: Employee ID
        in: path
        name: employee_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success Response
          schema:
            $ref: '#/definitions/internal_credential.DeleteResponseDto'
        "400":
          description: BadRequest
        "500":
          description: InternalServerError
      tags:
      - Credentials
  /credentials/{employee_id}/password:
    delete:
      description: Reset a credential's password
      parameters:
      - description: Employee ID
        in: path
        name: employee_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success Response
          schema:
            $ref: '#/definitions/internal_credential.PatchPasswordResponseDto'
        "400":
          description: BadRequest
        "500":
          description: InternalServerError
      tags:
      - Credentials
    patch:
      consumes:
      - application/json
      description: Patch a credential's password
      parameters:
      - description: Employee ID
        in: path
        name: employee_id
        required: true
        type: string
      - description: Password Patch Request
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/internal_credential.PatchPasswordRequestDto'
      produces:
      - application/json
      responses:
        "200":
          description: Success Response
          schema:
            $ref: '#/definitions/internal_credential.PatchPasswordResponseDto'
        "400":
          description: BadRequest
        "500":
          description: InternalServerError
      tags:
      - Credentials
  /profiles/{ehid}:
    delete:
      description: Delete a profile
      parameters:
      - description: Employee Hash ID
        in: path
        name: ehid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success Response
          schema:
            $ref: '#/definitions/internal_profile.DeleteResponseDto'
        "400":
          description: BadRequest
        "500":
          description: InternalServerError
      tags:
      - Profiles
    get:
      description: Get a profile
      parameters:
      - description: Employee Hash ID
        in: path
        name: ehid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success Response
          schema:
            $ref: '#/definitions/internal_profile.GetResponseDto'
        "400":
          description: BadRequest
        "500":
          description: InternalServerError
      tags:
      - Profiles
    patch:
      consumes:
      - application/json
      description: Patch a profile
      parameters:
      - description: Employee Hash ID
        in: path
        name: ehid
        required: true
        type: string
      - description: Profile Patch Request
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/internal_profile.PatchRequestDto'
      produces:
      - application/json
      responses:
        "200":
          description: Success Response
          schema:
            $ref: '#/definitions/internal_profile.PatchResponseDto'
        "400":
          description: BadRequest
        "500":
          description: InternalServerError
      tags:
      - Profiles
  /profiles/me/ehid:
    get:
      description: Get current user's EHID
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success Response
          schema:
            $ref: '#/definitions/internal_profile.GetEhidResponseDto'
        "400":
          description: BadRequest
        "500":
          description: InternalServerError
      tags:
      - Profiles
  /sessions:
    post:
      consumes:
      - application/json
      description: Post a new session
      parameters:
      - description: Session Request
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/internal_session.PostRequestDto'
      produces:
      - application/json
      responses:
        "200":
          description: Success Response
          schema:
            $ref: '#/definitions/internal_session.PostResponseDto'
        "400":
          description: BadRequest
        "401":
          description: Unauthorized
        "500":
          description: InternalServerError
      tags:
      - Sessions
swagger: "2.0"
